services:
  client:
    image: kimxuanvinh2002/retailclient:latest
    build:
      context: ./client
      target: production

  server:
    image: kimxuanvinh2002/retailserver:latest
    build:
      context: ./server
      target: production